# Generated by Django 5.2.17 on 2026-09-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
